# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  DOTNET_SDK_VERSION: '2.1.602'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '7.x'

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(DOTNET_SDK_VERSION)'
  inputs:
    version: '$(DOTNET_SDK_VERSION)'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'CoreWiki'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
